### ISSUE TITLE
File plugins do not actively obtain static route, but range is ok

### ISSUE THREAD

**Issue by attlee-wang** [coredhcp/coredhcp#157]
File plugins do not actively obtain static route, but range is ok.
- range  plugins
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/57479557/184609888-74688a83-76b4-456b-a348-673425d111e4.png">
- file plugins 

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/57479557/184610444-dfd48acf-e962-4c55-8412-ab3d5ec6826f.png">

**Comment by Natolumin** [comment]
I'll need more information to understand and reproduce the issue here. Can you share more about what and how you're testing ? In particular: 

* Which commit you're running if it's not the current master. I see a bunch of logs in your screenshots that I can't find anywhere in the code, so you seem to have modified the software ? If so please reproduce the issue on the current master first
* Show the configuration file that you're using. This is especially important since the file plugin stops execution when successful so you probably want it to be loaded last in your configuration

**Comment by attlee-wang** [comment]
@Natolumin  I have found this problem, I will fix it later.
