### ISSUE TITLE
Performance comparison with other dhcp clients

### ISSUE THREAD

**Issue by kovetskiy** [coredhcp/coredhcp#29]
Hey, thanks for the project, it sounds interesting, is there any table comparison with other dhcp clients such as dh-client, dhcpcd or systemd-networkd (interested only in dhcp mode)?

**Comment by insomniacslk** [comment]
Hey @kovetskiy, this is only a server, not a client, so that comparison would not be possible. The open source DHCP client scenario is much better than the server counterpart, so we didn't feel the need of providing a different client. However you can play with a sample client using the same DHCP library that we wrote, see https://github.com/insomniacslk/dhcp and the example under https://github.com/insomniacslk/exdhcp .

Hope that helps

**Comment by kovetskiy** [comment]
Hi, thanks for the reply.
