### ISSUE TITLE
plugins/file: Panic when importing file plugin

### ISSUE THREAD

**Issue by gbandres98** [coredhcp/coredhcp#61]
When I do `go get github.com/coredhcp/coredhcp` or when I run a go program that imports "github.com/coredhcp/coredhcp/plugins/file", I always get the following panic message:

`../../../github.com/coredhcp/coredhcp/plugins/file/plugin.go:163:6: invalid pointer type *dhcpv6.OptBootFileURL for composite literal`

What could be the reason for this? I have had no other problems with other packages. I have even tried reinstalling go and clearing my GOPATH folder.

Thank you very much.

**Comment by Natolumin** [comment]
What go version are you using (run `go version` in a terminal) ? This project uses go modules, which helps pin dependencies, but that is only supported after go 1.11, and enabled by default everywhere in go 1.13

This error you're seeing is caused by a breaking change in an upstream library, however you should not be encountering it since we have the version of that library pinned to an earlier commit.

If you have go >= 1.11, you can try running "GO111MODULE=on go get github.com/coredhcp/coredhcp" and it should get the proper versions of the dependencies

If you are developing with coredhcp and importing the plugins, you need to develop *outside* GOPATH and use go modules yourself so that dependent versions are correctly imported. You can check this go blog post for more details on go modules: https://blog.golang.org/using-go-modules

**Comment by gbandres98** [comment]
Hello @Natolumin, thanks for your help. We are using go 1.12.9, but running `GO111MODULE=on go get github.com/coredhcp/coredhcp` doesn't solve our problem, as we still get the same error using that package. Do you think there might be any other way to download an older version of the dependencies? We are not ready to migrate to go modules yet.

**Comment by Natolumin** [comment]
It might be possible to work around the issue by running `GO111MODULE=on go get github.com/insomniacslk/dhcp@834a63bade8a` (That is the offending dependency and after the @ is the commit id from the go.mod file).
Alternatively if module mode doesn't work at all, in GOPATH mode this should work (but will break as soon as you `go get -u` to update dependencies)
```
git -C $GOPATH/src/github.com/insomniacslk/dhcp checkout 834a63bade8a
go get github.com/coredhcp/coredhcp
```

Since I can't reproduce the issue here I'm not completely sure these will work, let me know if that at least works around the problem for now

**Comment by pmazzini** [comment]
I updated coredhcp to match the latest library changes: https://github.com/coredhcp/coredhcp/pull/62.

**Comment by gbandres98** [comment]
Thanks again @Natolumin. We haven't been able to work with GO111MODULE=on, but your second workaround did work for us. Thank you very much for your help.
