### ISSUE TITLE
Offer a Close or Shutdown interface to allow close DHCP server

### ISSUE THREAD

**Issue by guo1017138** [coredhcp/coredhcp#95]
Hi,

I am using coredhcp in multi-thread mode, I am able to create, Start() a DHCP server and Wait() for packets.
However, I want to end this thread with  DHCP shutdown/close gracefully. while my my main function can continue to do other tasks.

So, I'd like to request a Close() or Shutdown() method which can make Wait() exit gracefully without error.

Thank you.

**Comment by Natolumin** [comment]
Since #58 there is a [`server.Servers.Close()`](https://pkg.go.dev/github.com/coredhcp/coredhcp/server?tab=doc#Servers.Close) which should do what you want. 
You can optionally use `Wait()` after that to wait until all the server goroutines have exited (It will return an error if you've already called Close() which you can ignore

**Comment by guo1017138** [comment]
Thanks. Checked the latest code and the Close method is there. Closing the issue now.
